name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    environment: dg-cloud-vm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/wsgamer7/hello-docker-gcr-demo:latest
          docker run ghcr.io/wsgamer7/hello-docker-gcr-demo:latest
          docker push ghcr.io/wsgamer7/hello-docker-gcr-demo:latest
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 root@164.92.82.130 << 'EOF'
            docker login ghcr.io -u wsgamer7 -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/wsgamer7/hello-docker-gcr-demo:latest
            docker hello-docker-gcr-demo || true
            docker rm hello-docker-gcr-demo || true
            docker run -d --name hello-docker-gcr-demo -p 8765:3000 -e JWT_SECRET=${{ secrets.JWT_SECRET }} ghcr.io/wsgamer7/hello-docker-gcr-demo:latest
          EOF
